### PR TITLE
Added 'busy' command

### PR DESCRIPTION
**Pull request by PHLAK**
Implemented the 'busy' command.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/25/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/26/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/27/
Tests Passed, Yay.

**Comment by DavidCaudill** [comment]
:+1:

**Comment by DavidCaudill** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Pull request merged**
