### PR TITLE
README Improvements

### PR DESCRIPTION
**Pull request by PHLAK**
Added additional prerequisite and installation requirements to the README.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/8/
Tests Passed, Yay.

**Comment by uberscientist** [comment]
:+1:

**Comment by Penguin2600** [comment]
:seedling: :cold_sweat:

**Comment by DavidCaudill** [comment]
does this compile? +1 if it does.

**Pull request merged**
