### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by PHLAK**
- Fixed typo in the README prerequisites installation
- Fixed requirements.txt file name typo

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/12/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
seriously. test this please.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/15/

**Build Log**
_last 25 lines_

```
[...truncated 324 lines...]
added: get_json, match, xkcd
plugin: roll
added: roll
plugin: syncrooms_autotranslate
added: *roomlanguage
plugin: cleverbot
added: chat
plugin: urbandict
added: urbandict
plugin: stock
added: stock
EXCEPTION during plugin import: No module named 'lxml' @ plugins.hiztory
plugin: example_memory
added: *forgetaboutitforchat, *forgetaboutitforme, *rememberthisforchat, *rememberthisforme, *whatwasitforchat, *whatwasitforme
plugin: example_watchmembers
plugin: btc
added: btc, get_json
plugin: mentions
added: mention, pushbulletapi, setnickname
plugin: default
added: *config, echo, *hangout, *hangouts, *leave, *quit, *reload, *rename, *user, *users, version, *whereami, whoami
Exeptions found
Build step 'Execute shell' marked build as failure
Setting status of d5a3c356514acaaf1b319876e5ec8301c79ab1be to FAILURE with url http://bock.systems:8080/job/CircleBotCheck/15/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
test this please. i fixed the build. Fuck you for using lxml.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/16/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please. i want an accounting of full build time due to lxml.

**Comment by Penguin2600** [comment]
test this please.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/17/
Tests Passed, Yay.

**Pull request merged**
