### PR TITLE
removed lxml requirement

### PR DESCRIPTION
**Pull request by uberscientist**
y'all +1 this, I even ran tox on it.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/19/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Luv it :heart: :mushroom: :shipit: :baby_bottle: :+1: :non-potable_water:

**Comment by PHLAK** [comment]
Tested.  :hamburger:

**Comment by Penguin2600** [comment]
:white_check_mark: :de: :church: :fire: :laughing:

**Comment by PHLAK** [comment]
Resolved issue #17

**Pull request merged**
