### PR TITLE
Additional thoughts command improvements

### PR DESCRIPTION
**Pull request by PHLAK**
Improvements include:
- Moved additional functions into the main command function.
-  Command will now return `Hmmmmmm: <status_code>` when the request returns anything other than a 200
- Parses user input into a URL encoded string for the GET request
- ~~Increased random result selection pool from 5 to 8 for slightly more randomness~~

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/11/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
5 was enough randomness. -1
the regex on the input keeps bad shit out -1
the headers keep rate limiting at bay -1

the code i wrote isn't random, things in it have purpose.

**Comment by PHLAK** [comment]
**5 was enough randomness:**  That's fine, we'll keep it at 5

**the regex on the input keeps bad shit out:**  I replaced the regex with parse.quote_plus() to just URL encode the user input

**the headers keep rate limiting at bay:** I have been unable to hit the rate limit in my testing even spamming ~20 commands in a row.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/13/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please, it is shit

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/14/

**Build Log**
_last 25 lines_

```
[...truncated 104 lines...]
added: get_json, match, xkcd
plugin: roll
added: roll
plugin: syncrooms_autotranslate
added: *roomlanguage
plugin: cleverbot
added: chat
plugin: urbandict
added: urbandict
plugin: stock
added: stock
EXCEPTION during plugin import: No module named 'lxml' @ plugins.hiztory
plugin: example_memory
added: *forgetaboutitforchat, *forgetaboutitforme, *rememberthisforchat, *rememberthisforme, *whatwasitforchat, *whatwasitforme
plugin: example_watchmembers
plugin: btc
added: btc, get_json
plugin: mentions
added: mention, pushbulletapi, setnickname
plugin: default
added: *config, echo, *hangout, *hangouts, *leave, *quit, *reload, *rename, *user, *users, version, *whereami, whoami
Exeptions found
Build step 'Execute shell' marked build as failure
Setting status of 0437b27f05f1a95a6174c0b239344af7721bb41d to FAILURE with url http://bock.systems:8080/job/CircleBotCheck/14/ and message: Merged build finished.
```

Oh No...

**Comment by PHLAK** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/18/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/20/
Tests Passed, Yay.

**Pull request merged**
