### PR TITLE
Goplugin

### PR DESCRIPTION
**Pull request by Penguin2600**
3 Commits for one change? that's value.

### CODE REVIEW

**Comment by uberscientist** [comment]
:v:alu:+1:

**Comment by DavidCaudill** [comment]
aight

**Comment by Penguin2600** [comment]
I should probably close this and restructure my branch, those commit titles are bad and i should feel bad

**Comment by DavidCaudill** [comment]
This branch gave me coffee, but then my cancer cured it.

**Comment by PHLAK** [comment]
@Penguin2600 Don't close the PR, just fix what you want and push it to this branch.  The PR will reflect those changes.

**Comment by DavidCaudill** [comment]
Rewrite history

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle%20Bot%20Check/5/

**Build Log**
_last 25 lines_

```
[...truncated 27 lines...]
    if self.setupenv(venv):
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 396, in setupenv
    status = venv.update(action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 140, in update
    self.install_deps(action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 254, in install_deps
    self._install(deps, action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 322, in _install
    action=action, extraenv=extraenv)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 288, in run_install_command
    extraenv=extraenv, action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 383, in _pcall
    return action.popen(args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 100, in popen
    stdout=stdout, stderr=STDOUT)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 188, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Build step 'Execute shell' marked build as failure
Setting status of 7419d1ab1abc682e0d23bfb2113724338b66788f to FAILURE with url http://bock.systems:8080/job/Circle%20Bot%20Check/5/ and message: Merged build finished.
```

Oh No...

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/11/

**Build Log**
_last 25 lines_

```
[...truncated 33 lines...]
stderr: Cloning into 'hubot-web'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:endofline/hubot-web.git' into submodule path 'hubot-web' failed
Failed to recurse into submodule path 'hangupsbot'

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$6.execute(CliGitAPIImpl.java:893)
    at hudson.plugins.git.extensions.impl.SubmoduleOption.onCheckoutCompleted(SubmoduleOption.java:83)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1047)
    at hudson.scm.SCM.checkout(SCM.java:484)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1751)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Setting status of 7419d1ab1abc682e0d23bfb2113724338b66788f to FAILURE with url http://bock.systems:8080/job/Circle-Bot-Check/11/ and message: Merged build finished.
```

Oh No...

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/5/
Tests Passed, Yay.

**Pull request merged**
