### PR TITLE
pass in auth file, receive cookies

### PR DESCRIPTION
**Pull request by DavidCaudill**

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/7/
Tests Passed, Yay.

**Comment by PHLAK** [comment]
+1 to what is here though I have some optional recommendations/ideas:
- Add `#!/usr/bin/env python3` to the top so it will still work when running it with `./login.py`
- Add a flag to allow the credentials to be provided vial the command line (i.e. - `python3 login.py --auth-user jpinkerton --auth-password p00pD@wg321`)
- Add a flag to control where the cookie.json file is created instead of putting it in the default location (i.e. - `python3 login.py --out some/path/cookies.json`)

**Comment by DavidCaudill** [comment]
third options is already in, --cookies

**Comment by uberscientist** [comment]
:+1:

**Pull request merged**
