### PR TITLE
Added README

### PR DESCRIPTION
**Pull request by PHLAK**
Added a basic README file.

### CODE REVIEW

**Comment by DavidCaudill** [comment]
someone who makes a readme in markdown, noice

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle%20Bot%20Check/1/

**Build Log**
_last 25 lines_

```
[...truncated 32 lines...]
    if self.setupenv(venv):
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 396, in setupenv
    status = venv.update(action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 140, in update
    self.install_deps(action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 254, in install_deps
    self._install(deps, action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 322, in _install
    action=action, extraenv=extraenv)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 288, in run_install_command
    extraenv=extraenv, action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 383, in _pcall
    return action.popen(args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 100, in popen
    stdout=stdout, stderr=STDOUT)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 188, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Build step 'Execute shell' marked build as failure
Setting status of 56264f3fbc72d3d65c64a336b83a84e21b84a814 to FAILURE with url http://bock.systems:8080/job/Circle%20Bot%20Check/1/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
cool story.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/6/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/7/

**Build Log**
_last 25 lines_

```
[...truncated 39 lines...]
Cloning into 'hubot-web'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:endofline/hubot-web.git' into submodule path 'hubot-web' failed
Failed to recurse into submodule path 'hangupsbot'

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$6.execute(CliGitAPIImpl.java:893)
    at hudson.plugins.git.extensions.impl.SubmoduleOption.onCheckoutCompleted(SubmoduleOption.java:83)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1047)
    at hudson.scm.SCM.checkout(SCM.java:484)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1751)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Setting status of 56264f3fbc72d3d65c64a336b83a84e21b84a814 to FAILURE with url http://bock.systems:8080/job/Circle-Bot-Check/7/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/12/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/13/

**Build Log**
_last 25 lines_

```
[...truncated 22 lines...]
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1751)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: hudson.plugins.git.GitException: Command "git checkout -f 12cc66ec54129310772623312fd1b1975b6b7bf7" returned status code 1:
stdout: 
stderr: error: unable to unlink old 'plugins/btc.py' (Permission denied)
error: unable to unlink old 'plugins/dilbert.py' (Permission denied)
error: unable to unlink old 'plugins/eightball.py' (Permission denied)
error: unable to unlink old 'plugins/prs.py' (Permission denied)
error: unable to unlink old 'plugins/roll.py' (Permission denied)
error: unable to unlink old 'plugins/slap.py' (Permission denied)
error: unable to unlink old 'plugins/stock.py' (Permission denied)
error: unable to unlink old 'plugins/thoughts.py' (Permission denied)
error: unable to unlink old 'plugins/xkcd.py' (Permission denied)
HEAD is now at 12cc66e... Merge 56264f3fbc72d3d65c64a336b83a84e21b84a814 into 0bc3cae99bc166178a1ee1e8288cf65fccf71ef5

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1850)
    ... 10 more
Setting status of 56264f3fbc72d3d65c64a336b83a84e21b84a814 to FAILURE with url http://bock.systems:8080/job/Circle-Bot-Check/13/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/14/
Tests Passed, Yay.

**Comment by uberscientist** [comment]
test this please one more time
murge it +1

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/15/

**Build Log**
_last 25 lines_

```
[...truncated 34 lines...]
    at hudson.scm.SCM.checkout(SCM.java:484)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1751)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Setting status of 56264f3fbc72d3d65c64a336b83a84e21b84a814 to FAILURE with url http://bock.systems:8080/job/Circle-Bot-Check/15/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Circle-Bot-Check/16/

**Build Log**
_last 25 lines_

```
[...truncated 27 lines...]
    at hudson.scm.SCM.checkout(SCM.java:484)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1751)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Setting status of 56264f3fbc72d3d65c64a336b83a84e21b84a814 to FAILURE with url http://bock.systems:8080/job/Circle-Bot-Check/16/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/1/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/6/
Tests Passed, Yay.

**Pull request merged**
