### PR TITLE
thoughts command improvements

### PR DESCRIPTION
**Pull request by PHLAK**
- Now using api.reddit.com endpoint and HTTPS
- Limit to 5 results returned and reduced randomization LoC
- No more linking
- Added response when no arguments supplied

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/31/
Tests Passed, Yay.

**Comment by DavidCaudill** [comment]
this kills the thoughts command
would recommend just making a reddit command and leave the current functionality of the thoughts command
-1

**Comment by uberscientist** [comment]
ah yes, the spirit of the thoughts command was for the bot to use reddit thread titles as it's own random thoughts about `args`

this seperated out to a reddit command might be a good idea, maybe even "improve" thoughts to use some sort of markov thing for another layer of lels

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/CircleBotCheck/33/
Tests Passed, Yay.

**Comment by uberscientist** [comment]
:+1: I'll get my brain game on and learn about some Markov chains (after I do some other stuff here... humm hmmmmm!)

**Pull request merged**
